// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiRhsRaWEbk0giAlp7wcTmdHhgYJyF5nU',
    appId: '1:632159136590:web:72ec73f7676a227f6e0c1f',
    messagingSenderId: '632159136590',
    projectId: 'fooddelivery-e5d62',
    authDomain: 'fooddelivery-e5d62.firebaseapp.com',
    storageBucket: 'fooddelivery-e5d62.appspot.com',
    measurementId: 'G-VTF22XSV4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfGqL2fa1kul-9mwbP_FdHc78FxyV53d0',
    appId: '1:632159136590:android:46547fc9fc3358bd6e0c1f',
    messagingSenderId: '632159136590',
    projectId: 'fooddelivery-e5d62',
    storageBucket: 'fooddelivery-e5d62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM4mTK5AY_9iAWGe-ZGwWShbIqLLgONrI',
    appId: '1:632159136590:ios:7299107e5893440c6e0c1f',
    messagingSenderId: '632159136590',
    projectId: 'fooddelivery-e5d62',
    storageBucket: 'fooddelivery-e5d62.appspot.com',
    iosBundleId: 'com.example.bandoan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM4mTK5AY_9iAWGe-ZGwWShbIqLLgONrI',
    appId: '1:632159136590:ios:7299107e5893440c6e0c1f',
    messagingSenderId: '632159136590',
    projectId: 'fooddelivery-e5d62',
    storageBucket: 'fooddelivery-e5d62.appspot.com',
    iosBundleId: 'com.example.bandoan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiRhsRaWEbk0giAlp7wcTmdHhgYJyF5nU',
    appId: '1:632159136590:web:5c37179ffa32fc9e6e0c1f',
    messagingSenderId: '632159136590',
    projectId: 'fooddelivery-e5d62',
    authDomain: 'fooddelivery-e5d62.firebaseapp.com',
    storageBucket: 'fooddelivery-e5d62.appspot.com',
    measurementId: 'G-EZK0098M4P',
  );
}
